create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" text not null unique,
  name text,
  email text,
  "loginMethod" text,
  role text not null default 'user' check (role in ('user', 'admin')),
  "totalInvested" numeric(15,2) not null default 0,
  "totalEarnings" numeric(15,2) not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.investment_plans (
  id bigint generated by default as identity primary key,
  name text not null,
  "minAmount" numeric(15,2) not null,
  "maxAmount" numeric(15,2),
  roi numeric(5,2) not null,
  duration integer not null,
  description text,
  features jsonb not null default '[]'::jsonb,
  "displayOrder" integer not null default 0,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.investment_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  "expectedYield" text not null,
  "riskLevel" text not null check ("riskLevel" in ('low', 'medium', 'high')),
  "displayOrder" integer not null default 0,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.user_investments (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references public.users(id) on delete cascade,
  "planId" bigint not null references public.investment_plans(id),
  "categoryId" bigint not null references public.investment_categories(id),
  amount numeric(15,2) not null check (amount > 0),
  "expectedReturn" numeric(15,2) not null check ("expectedReturn" >= 0),
  status text not null default 'pending' check (status in ('pending', 'active', 'completed', 'withdrawn')),
  "stripePaymentId" text,
  "startDate" timestamptz,
  "endDate" timestamptz,
  "actualReturn" numeric(15,2) not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references public.users(id) on delete cascade,
  amount numeric(15,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'completed')),
  reason text,
  "approvedBy" bigint references public.users(id),
  "approvalDate" timestamptz,
  "rejectionReason" text,
  "completedAt" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  "adminId" bigint not null references public.users(id),
  action text not null,
  "targetUserId" bigint references public.users(id),
  "targetInvestmentId" bigint references public.user_investments(id),
  details jsonb,
  "createdAt" timestamptz not null default now()
);

create index if not exists user_investments_user_id_idx on public.user_investments ("userId");
create index if not exists withdrawal_requests_user_id_idx on public.withdrawal_requests ("userId");
create index if not exists withdrawal_requests_status_idx on public.withdrawal_requests (status);

alter table public.users enable row level security;
alter table public.investment_plans enable row level security;
alter table public.investment_categories enable row level security;
alter table public.user_investments enable row level security;
alter table public.withdrawal_requests enable row level security;
alter table public.admin_logs enable row level security;

create policy "public can read active plans" on public.investment_plans for select to anon, authenticated using ("isActive" = true);
create policy "public can read active categories" on public.investment_categories for select to anon, authenticated using ("isActive" = true);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new."updatedAt" = now(); return new; end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists investment_plans_set_updated_at on public.investment_plans;
create trigger investment_plans_set_updated_at before update on public.investment_plans for each row execute function public.set_updated_at();
drop trigger if exists investment_categories_set_updated_at on public.investment_categories;
create trigger investment_categories_set_updated_at before update on public.investment_categories for each row execute function public.set_updated_at();
drop trigger if exists user_investments_set_updated_at on public.user_investments;
create trigger user_investments_set_updated_at before update on public.user_investments for each row execute function public.set_updated_at();
drop trigger if exists withdrawal_requests_set_updated_at on public.withdrawal_requests;
create trigger withdrawal_requests_set_updated_at before update on public.withdrawal_requests for each row execute function public.set_updated_at();
